Fix conflicting types error in clang modules build
When I introduce clang modules build to macOS for chromium, I saw error
like

```
../../third_party/swiftshader/third_party/llvm-10.0/llvm/lib/ExecutionEngine/RuntimeDyld/RTDyldMemoryManager.cpp:45:17: error: conflicting types for '__deregister_frame'
   45 | extern "C" void __deregister_frame(void *);
      |                 ^
../../build/mac_files/xcode_binaries/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/unwind.h:140:13: note: previous declaration is here
  140 | extern void __deregister_frame(const void *fde);
      |             ^
```

To fix the error, this changes type of function argument.

Bug: 425535758
Change-Id: Idd26e1b0ef5bfa42413e03ef2edfec53ed2b9096
Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/75808
Tested-by: Shahbaz Youssefi <syoussefi@google.com>
Commit-Queue: Shahbaz Youssefi <syoussefi@google.com>
Kokoro-Result: kokoro <noreply+kokoro@google.com>
Reviewed-by: Shahbaz Youssefi <syoussefi@google.com>